### ISSUE TITLE
[Eidolon][Gradual Ability Boost]Module's Eidolon Ability boost progression is unable to follow Gradual Ability Boost optional rule if enabled

### ISSUE THREAD

**Issue by LordWillmont** [TikaelSol/PF2e-Animal-Companions#101]
If Gradual Ability Boost optional rule is active, you are unable to increase ability for your Eidolon by GAB rules, only by pop-out widow that appears upon reaching corresponding levels (original Ability Boost rules)

_Please note, that there is workaround by enabling manual entry for Ability Boost progression and manually change abilities each time you gain such boost._

Steps-to-reproduce:

1. Enable Gradual Ability Boost optional rule (In System Settings)
2. Create Character Sheet
3. Add any Eidolon Ancestry to newly-created charsheet
4. Level-up Eidolon to 2nd level
5. Attempt to add boost via Ability Boost option in character sheet.

**Comment by TikaelSol** [comment]
I'm not going to support variant rules with this module, sorry.
