### ISSUE TITLE
EC Wolf Description Not Reflecting Accurate Information

### ISSUE THREAD

**Issue by roxim5** [TikaelSol/PF2e-Animal-Companions#14]
Was looking at the Blood Wolf and the Description is a direct copy paste from the regular Wolf and does not show the following:
- 8 HP
- Darkvision
- Intimidation as trained Skill
![image](https://user-images.githubusercontent.com/89946334/147500570-6eff111d-c254-457a-89a6-c398905f89e2.png)

**Comment by TikaelSol** [comment]
Fixed as a stealth release.
