### ISSUE TITLE
Mature Animal Companion Feat sets size to medium and cannot be changed

### ISSUE THREAD

**Issue by metalflow** [TikaelSol/PF2e-Animal-Companions#15]
This feat sets the size on the character sheet to medium, regardless of what is set in the ancestry feat.  This feat also lacks any ability to control the animal companion size, so I am not sure how it is accomplishing that.

**Comment by TikaelSol** [comment]
This is fixed in the next release of the module, which will be released on the 14th after the pf2e system update since I'm using features that will be released in it. You can edit the rule elements on the feat for now to remove the size override.
