### ISSUE TITLE
Eidolon Primary Attack

### ISSUE THREAD

**Issue by dogstarrb** [TikaelSol/PF2e-Animal-Companions#16]
The eidolon primary attacks are not configured correctly. The reference document says the options are:
    1d8 damage (disarm, nonlethal, shove, or trip)
    1d6 damage (fatal d10)
    1d6 damage (forceful and sweep)
    1d6 damage (deadly d8 and finesse)
That seems to be interpreted by the options in the module as 1d8 with disarm and nonlethal and (shove or trip) when in actuality it should be read as (disarm OR nonlethal OR shove OR trip) resulting in 4 different configurations for the 1d8 damage options, not two which MUST have disarm and nonlethal.

**Comment by TikaelSol** [comment]
Missed the comma when reading, fixed in 5.0.2
