### ISSUE TITLE
Adding Beast and Phantom Eidolon ancestries are crashing the programme

### ISSUE THREAD

**Issue by JudgeNash** [TikaelSol/PF2e-Animal-Companions#22]
Creating a new PC (for an Eidolon), using the pf2e module, when dragging the Beast and Phantom Eidolon ancestries are added, once you click on a Primary Strike, it crashes the tab completely. Tested on Firefox and Chrome. No other modules are installed, only this one. Can replicate on both browsers.

Added this on PF2e hub but got told it's not core so adding here as well. Hope that's ok!

**Comment by TikaelSol** [comment]
This is actually a core system issue. Fixed by https://gitlab.com/hooking/foundry-vtt---pathfinder-2e/-/merge_requests/7750 whenever it gets reviewed and merged.
