### ISSUE TITLE
Specialiced Animal companions dont gain all Baseline benefits

### ISSUE THREAD

**Issue by Nelzy** [TikaelSol/PF2e-Animal-Companions#23]
Specialized animal companions dont gain the baseline "Increase its Dexterity modifier by 1 and its Intelligence modifier by 2" or damage increase that all animal companions gain when they get there first specialization.

They get all other things and the listed unique for that specialization.

> Specialized animal companions are more intelligent and engage in more complex behaviors. The first time an animal gains a specialization, it gains the following: Its proficiency rank for unarmed attacks increases to expert. Its proficiency ranks for saving throws and Perception increase to master. Increase its Dexterity modifier by 1 and its Intelligence modifier by 2. Its unarmed attack damage increases from two dice to three dice, and it increases its additional damage with unarmed attacks from 2 to 4 or from 3 to 6.
> 
> Each specialization grants additional benefits. Most animal companions can have only one specialization.

As and Example, a Savage, Mature Horse that selects Ambush specification Gains:
Expert in unarmed attacks (Generic specialization)
Expert in Unarmored (Specific for Ambush)
Expert in Stealth (Specific for Ambush)
Master in Perception (Generic specialization)
Master in all Saves (Generic specialization)
Increase Dexterity modifier by 1 (Specific for Ambush)
From 2 -> 3 Dice on attacks (Generic specialization)

But whats missing is
Increase Dexterity modifier by 1 (Generic specialization)
Increase Intelligence modifier by 2 (Generic specialization)
increases its additional damage with unarmed from 3 to 6. (Generic specialization)

Foundry Varsion 9
Pathfinder2e 3.7.2.1
PF2e Companion compendia 5.0.9

**Comment by TikaelSol** [comment]
This is related to a system bug. It appears AE like rule elements are not having their predicates tested properly. As soon as that is fixed the module will work properly again.
