### ISSUE TITLE
Fix a typo in Crocodile ancestry

### ISSUE THREAD

**Issue by rectulo** [TikaelSol/PF2e-Animal-Companions#24]
<p><strong>Support Benefit</strong> Your crocodile clamps its jaws on your foe, refusing to let go. Until the start of your next turn, if your Strike damages a creature in your crocodile's reach, your crocodile can latch onto the creature. While thus attached, the crocodile can move along with the target whenever the target moves until the end of your next turn. Your crocodile can latch onto only one creature in this way, and it must release the creature to make a jaws Strike. If the target is smaller than the crocodile, it takes a -10-foot circumstance penalty to its**</p>
<p><strong>Speed</strong>s** and can't Fly while the crocodile is latched on.</p>

**Comment by TikaelSol** [comment]
Closed in v5.10, release expected April 27th.
