### ISSUE TITLE
Fix the scorpion stinger attack format

### ISSUE THREAD

**Issue by rectulo** [TikaelSol/PF2e-Animal-Companions#27]
Scorpion ancestry :   
replace 
```
<p><strong>Melee</strong> <span class="pf2-icon">1</span> stinger, <strong>Damage</strong> 1d6 piercing</p>
<p>plus poison (see Special)</p>
```

by 
`<p><strong>Melee</strong> <span class="pf2-icon">1</span> stinger, <strong>Damage</strong> 1d6 piercing plus poison (see Special)</p>`

**Comment by TikaelSol** [comment]
Closed in v5.10, release expected April 27th.
