### ISSUE TITLE
Angel Eidolon Hallowed Strikes Target

### ISSUE THREAD

**Issue by leerhund** [TikaelSol/PF2e-Animal-Companions#32]
The current RE to apply 1 Good damage to Evil targets isn't working at the moment.
`{"key":"FlatModifier","selector":"strike-damage","value":1,"damageType":"good","predicate":{"all":["target:evil"]}}`

Changing the preficate to `target:trait:evil` seems to correct that.

**Comment by TikaelSol** [comment]
Resolved in 5.2
