### ISSUE TITLE
Eidolons are getting HP

### ISSUE THREAD

**Issue by leerhund** [TikaelSol/PF2e-Animal-Companions#33]
The following REs are currently on the Eidolon Class item, granting them their Con mod in HP per level
`{"key":"FlatModifier","selector":"hp-per-level","type":"item","value":"-@actor.data.data.abilities.con.mod"}`

And just 1 HP flat
`{"key":"FlatModifier","selector":"hp","type":"item","value":1}`

**Comment by leerhund** [comment]
Removing the Flat HP sets it back to showing 0 HP

**Comment by TikaelSol** [comment]
Resolved in 5.2
