### ISSUE TITLE
two different attacks roll the same for damage

### ISSUE THREAD

**Issue by dhon** [TikaelSol/PF2e-Animal-Companions#35]
First let me say that this might not be an issue with this module, and it is a more generic issue, but I wasn't sure how to verify.
I've noticed this on all companions with two types of attacks (Bear, Dromaeosaur, etc).

I will use Dromaeosaur for the following example:
When looking at the actions list, all buttons for both attacks (Talon, Jaws) look and work correctly. 

However if you click the Jaws Strike button, then in the game chat click the Damage or Critical buttons, it will roll damage for Talons.
This seems to be the case for all of them, the 'Damage' roll from the chat for both attack options pick the same one regardless.

(Ignore me having 3 copies of each attack, I added custom inventory weapons to fix the above issue)
![damage rolls](https://user-images.githubusercontent.com/14957824/170889997-19ec067b-8c7c-4fe0-9f43-ef679d01f748.gif)

**Comment by TikaelSol** [comment]
This is an issue with a core system function, unrelated to this module. Closing and will investigate the bug in the pf2e system.
