### ISSUE TITLE
Unable To Create Companion -- e.uuid is undefined

### ISSUE THREAD

**Issue by mam8cc** [TikaelSol/PF2e-Animal-Companions#43]
Trying to create a new eidelon and getting the error `e.uuid is undefined`.  Using the official Abomination Vaults world from FVTT.

<img width="686" alt="image" src="https://user-images.githubusercontent.com/1774337/190883329-d1df2a54-0f35-484c-aff9-23453071b5ec.png">

To reproduce:
1. Create a new PC sheet
2. Drag the Undead Eidelon onto the sheet

<img width="307" alt="image" src="https://user-images.githubusercontent.com/1774337/190883360-c026d4dd-8b9a-4160-8e66-4d9f016cd60b.png">

<img width="686" alt="image" src="https://user-images.githubusercontent.com/1774337/190883375-77a68840-2259-4b90-9bc8-0c1c8446c7aa.png">

**Comment by TikaelSol** [comment]
Module is not yet v10 compatible, it will be in the next update which is happening soon.

**Comment by TikaelSol** [comment]
You submitted this as I was finishing work on the update by the way 😆

**Comment by mam8cc** [comment]
Shoot, should have checked the compatibility in the `module.json` first.
Thank you for your hard work.
