### ISSUE TITLE
Version 9 Support

### ISSUE THREAD

**Issue by Noggog** [TikaelSol/PF2e-Animal-Companions#44]
Hey Tikael!

I happen to be in the unfortunate spot of building my Foundry setups in between major version updates.   Lots of mods I'd like to use only work for v9 still, so it would be nice to have v9 support for a bit longer until everyone else stabilizes.

Are you able to expose 5.3 for a bit longer?

I've seen other authors able to do this via tagging the commit involved, and adding another module.json pointing to that tag:
https://github.com/schlosrat/token-health

**Comment by TikaelSol** [comment]
[pf2e-animal-companions.zip](https://github.com/TikaelSol/PF2e-Animal-Companions/files/9594223/pf2e-animal-companions.zip)

There's version 5.3 zipped up, I made a release for 5.3 so others can find it but doesn't look like it's going to let me properly set up the release after the fact to work with Foundry.
