### ISSUE TITLE
Feature Request (or update documentation) for Summoner Archetype Eidolons

### ISSUE THREAD

**Issue by jrmiller82** [TikaelSol/PF2e-Animal-Companions#49]
I think having a toggle on the sheet that lets it know that it is a Summoner Archetype Eidolon instead of a full eidolon would be helpful. I banged my head around wondering why I couldn't change the 18 in an ability score to a 16. I just deleted the type of eidolon from the feat page and then added an untyped modifier to get an AC bump (brutal beast). 

If there is already a way to do this correctly, I apologize for being dense and not able to figure it out myself. In that case, maybe a paragraph on the README about summoner archetype eidolons? 

Thank you so much for making this module. It's super helpful.

**Comment by TikaelSol** [comment]
Fixed in 5.5.

There is now a Summoner Dedication Adjustment feat in CC Evolution Feats that caps all stats at 16 until level 5.
