### ISSUE TITLE
Mature Companions and Automatic Bonus Progression Variant

### ISSUE THREAD

**Issue by vesticles** [TikaelSol/PF2e-Animal-Companions#51]
Noticed when a world is using the "Automatic Bonus Progression" variant rule and an animal companion takes the "Mature Animal Companion" feat, it adds an extra die (3 total instead of 2)

Level 4 companion w/o feat
![image](https://user-images.githubusercontent.com/123271289/213886355-be044340-b8f9-46ad-88f8-62af65a770c6.png)
![image](https://user-images.githubusercontent.com/123271289/213886369-cbf24091-6054-4369-9530-2a51abdedeae.png)

Level 4 companion with feat
![image](https://user-images.githubusercontent.com/123271289/213886386-6f820fb9-98c1-4e23-a94a-52e1ac3ed8f6.png)
![image](https://user-images.githubusercontent.com/123271289/213886398-dfe4269e-3001-46f1-a6dc-f696d2d01b00.png)

**Comment by TikaelSol** [comment]
This is not an issue with the module, it's a system bug ignoring the flag on companions.
