### ISSUE TITLE
Override Eidolon spell DC to match summoner's

### ISSUE THREAD

**Issue by Mejari** [TikaelSol/PF2e-Animal-Companions#54]
Using the Magical Understudy feat my Eidolon has access to some cantrips. The Summoner rules state that for these cantrips the summoner's spell DC and spell attack modifier. 

It would be nice to be able to modify the Eidolon's values, either to link them to the Summoner's (best solution, probably harder) or just be able to manually override them myself to match.

**Comment by TikaelSol** [comment]
This is out of scope for this module, it does not have any way to form any link between the two actors.
