### ISSUE TITLE
Zombie companion has bear support benefit

### ISSUE THREAD

**Issue by SomeOctopus** [TikaelSol/PF2e-Animal-Companions#56]
The [zombie companion](https://2e.aonprd.com/AnimalCompanions.aspx?ID=45&Undead=true) ancestry created by this mod appears to have the Bear Support Benefit, a generic Fist strike language in actions, and no move speed. See attached screenshots.
![image](https://user-images.githubusercontent.com/125411475/218875088-11b88d33-1164-48d7-9c27-e256156cce83.png)
![image](https://user-images.githubusercontent.com/125411475/218875130-7f2bd2b0-a7d3-4887-84d1-538d93904d09.png)

Thanks for your help! Great module.

**Comment by TikaelSol** [comment]
Fixed the label and the support benefit but that's the other speed types field, look up for the land speed on the sheet

![image](https://user-images.githubusercontent.com/80183198/222937846-b6c271a8-4fb1-4ed4-9f5e-528ccf37f966.png)
