### ISSUE TITLE
Expired effects aren't removed from Eidolons

### ISSUE THREAD

**Issue by this-gavagai** [TikaelSol/PF2e-Animal-Companions#59]
Thank you so much for this fantastic module. It has really improved our table's game.

One minor issue I've noticed is with time-bound effects. Under the pf2e automation settings, it is possible to mark that expired effects should be removed automatically. This works, but it doesn't seem to work for companion characters (eidolons specifically). I assume this has something to do with the fact that eidolons and other companions don't show up in the combat tracker, but I definitely don't know for sure. Is there any way to make the automation work here?

Thanks again for all the hard work you've done!

**Comment by TikaelSol** [comment]
This is something the system would need to address. We'll look into it there.

**Comment by this-gavagai** [comment]
Awesome, thank you so much for the work you do!
