### ISSUE TITLE
Eidolons ignore main bonus progression screen.

### ISSUE THREAD

**Issue by Teraunce** [TikaelSol/PF2e-Animal-Companions#63]
This breaks things when using the alternate Staggered Ability Score Bonus rule (instead of gaining all 4 picks at level 5, 10, 15, and 20 you get 1 each at 2, 3, 4, and 5 then 7, 8, 9, and 10 and so on.) Pleaso stop hardcoding such stuff.

**Comment by TikaelSol** [comment]
I do not plan on accommodating variant rules in this module.
