### ISSUE TITLE
Error with Highhelm's goat

### ISSUE THREAD

**Issue by neo2005** [TikaelSol/PF2e-Animal-Companions#72]
Hi,

Highhelm's goat has incorrect the land speed and doesn't have the climb speed. I try to fix the problem and make a pull request, but I don't know the correct method to open the files. 

I would appreciate if you could tell me how to do it for future errors.

**Comment by VoidsCL** [comment]
Where are you getting the highhelm goat? I came here actually to ask if they could add the companions from LO:H since I can't find them in the compendium.

Is it in the v11 version?

**Comment by TikaelSol** [comment]
Fixed in 5.9.

@VoidsCL Yes, goat was added after the module jumped to v11. I will not be adding new content to the v10 version of the module.
