### ISSUE TITLE
Overdrive doesn't apply properly to construct companion.

### ISSUE THREAD

**Issue by Sharpenme** [TikaelSol/PF2e-Animal-Companions#76]
Perhaps I'm missing something, but I don't see an alternative buff to drop on a construct companion to give it the buff from overdrive. If you add overdrive as it stands to the companion, the companion's Int is referenced.

**Comment by TikaelSol** [comment]
Send the overdrive action to chat first, then drag the effect from there onto the companion. If that isn't working then it's a system issue.
