### ISSUE TITLE
Animal Companions are affected by the Automatic Bonus Progression variant rule.

### ISSUE THREAD

**Issue by OtmicusRX** [TikaelSol/PF2e-Animal-Companions#8]
In my game, I activated the Automatic Bonus progression variant rule, considering the bonus progression as fundamental runes.
However, when I added our Ranger's Animal Companion and Beastmaster companion using the PF2e Animal Companions module, I noticed that both of them had the Bonus Progression applied as well, which shouldn't be the case.

**Comment by TikaelSol** [comment]
This problem isn't fixable inside the module itself, it will get solved eventually when the module is integrated into core after an animal companion sheet is made.  But in the meantime I'll see if we can apply a patch to the system's implementation of ABP to check the class name for "Animal Companion".

**Comment by TikaelSol** [comment]
Nikolaj added a flag to disable ABP on a per actor basis.  It can be set with a macro:  token.actor.setFlag('pf2e','disableABP', true)

Or set with a rule element.

{
    "key": "PF2E.RuleElement.SetProperty",
    "property": "flags.pf2e.disableABP",
    "on": {
        "added": true,
        "removed": false
    },
    "retain": true
}

Which can be added to any owned item.  I have not tested these as the fix on the system side is not merged in yet.  I'm busy until July but I'll get the module updated to set this flag by default once I have time.

**Comment by OtmicusRX** [comment]
Sorry for replying so late, but both options do not seem to be working in my game. I added the rule to a wolf animal companion's bite attack, and also ran the macro on the wolf's token, but the modifiers are still there.

**Comment by TikaelSol** [comment]
Make sure your PF2e system is up to date, and if it still doesn't work go to the #pf2e channel in the Foundry discord and they should be able to figure out what's happening.

**Comment by TikaelSol** [comment]
Closed with version 2.0
