### ISSUE TITLE
[Bug] Negative HP while using the Stamina variant rules

### ISSUE THREAD

**Issue by Wotn9** [TikaelSol/PF2e-Animal-Companions#80]
![image](https://github.com/TikaelSol/PF2e-Animal-Companions/assets/45216414/3fe675d3-ff46-458d-9820-5b752d26b5cb)
Linking Eidolon with Summoner HP is incorrect, as the Eidolon level up it keeps losing 3 hp.
How to reproduce : 
- Activate Stamina
- Set any eidolon ancestry

Workaround : It seems to almost work if we set the Eidolon character sheet before enabling stamina variant rule.

**Comment by TikaelSol** [comment]
I don't plan on supporting variant rules with this module.
