### ISSUE TITLE
Nature skill cannot be Untrained on Eidolon

### ISSUE THREAD

**Issue by ShadowDrakken** [TikaelSol/PF2e-Animal-Companions#85]
Module version: 6.1

I'm not able to set Nature as Untrained from the Beast (Fleet) Eidolon. I can set it to anything else however.

**Comment by MrVauxs** [comment]
Beast Eidolons have Nature as their given proficiency. You cannot set it as untrained because its set by the Beast Eidolon ancestry.

Modify the rule element if you want to change the proficiency.
