### ISSUE TITLE
Missing Releases

### ISSUE THREAD

**Issue by MrZeyami** [TikaelSol/PF2e-Animal-Companions#93]
Came over to check if the module has been updated to v12 and saw that every release after v5.9 is now missing.
Couldn't find anything searching around and am hoping I don't need to uninstall v6.3 due to some unforeseen major issue.

**Comment by TikaelSol** [comment]
I only do github releases when needed to preserve a version for people more easily. The current version is 6.3 and is what gets installed in Foundry or what you get if you check out the current main branch of the module. 5.9 is just the last "release" I made here to preserve a pre-remaster version of the module.
