### ISSUE TITLE
Plant/Fungus Companions?

### ISSUE THREAD

**Issue by eballard1** [TikaelSol/PF2e-Animal-Companions#95]
I was curious if there was a plan to implement the Leshy companion features that allow the building of a plant/fungus companion? Thanks

**Comment by TikaelSol** [comment]
What book is that from? I don't have plans to really incorporate much into this anymore since I have other things to do and the system will be including proper companion support later this year.

**Comment by Zelandros** [comment]
I came in to ask the same thing, the Leshy familiar is in the core rulebook (legacy) and Player core (remastered) it is a druid feat companion

**Comment by TikaelSol** [comment]
Ah, familiars are not a part of this module. The system has a familiar actor, but no support for specific familiars.
