### ISSUE TITLE
Eidolon Weapon Specialization is not applied

### ISSUE THREAD

**Issue by coriolis-storm** [TikaelSol/PF2e-Animal-Companions#99]
I've been building and testing a summoner for a new campaign I'm starting, and Eidolon Weapon Specialization (level 7 class feature) isn't being applied to the eidolon's attacks, even though it appears in the Class Feature section correctly.

**Comment by coriolis-storm** [comment]
On a hunch, I also checked Greater Eidolon Specialization at level 15, and it's also not applied.

**Comment by olilan1** [comment]
I saw this too.

I think the issue is that Eidolon Weapon Specialization's predicates refer to things like `proficiency:rank:2` but it should be `item:proficiency:rank:2`
